apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: sample-app-route
spec:
  routes:
    - match: Host(`sample-app.zakhassan.com`)
      kind: Rule
      services:
        - name: sample-app
          kind: Service
          port: 80