apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/zmhassan/sample-app.git
    targetRevision: HEAD
    path: helm/sample-app
  destination:
    server: https://kubernetes.default.svc
    namespace:  sample-app